# Generated by Django 3.1.2 on 2020-10-16 17:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('type', models.CharField(choices=[('1', 'goods'), ('2', 'Electronics'), ('3', 'Games'), ('4', 'Fashion'), ('5', 'Furniture'), ('6', 'Real Estate'), ('7', 'Food'), ('8', 'Equipment'), ('9', 'Books'), ('10', 'pets'), ('11', 'Business - Industrial'), ('12', ' Craftsmen'), ('13', 'Electrician services'), ('14', 'Travel - Tourism'), ('15', 'Medical Services'), ('16', 'Events Services'), ('17', 'Teaching & Training'), ('18', 'Others')], default='18', max_length=18)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('1', 'goods'), ('2', 'services')], default='1', max_length=2)),
                ('phone', models.CharField(max_length=64)),
                ('email', models.CharField(max_length=64)),
                ('address', models.CharField(max_length=64)),
                ('price', models.CharField(max_length=64)),
                ('img', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
