# Generated by Django 3.1.2 on 2020-10-16 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.AlterField(
            model_name='shop',
            name='type',
            field=models.CharField(choices=[('1', 'cars'), ('2', 'Electronics'), ('3', 'Games'), ('4', 'Fashion'), ('5', 'Furniture'), ('6', 'Real Estate'), ('7', 'Food'), ('8', 'Equipment'), ('9', 'Books'), ('10', 'pets'), ('11', 'Business - Industrial'), ('12', ' Craftsmen'), ('13', 'Electrician services'), ('14', 'Travel - Tourism'), ('15', 'Medical Services'), ('16', 'Events Services'), ('17', 'Teaching & Training'), ('18', 'Others')], default='18', max_length=18),
        ),
    ]
