version: '3.8'

services:
    web:
        build: .
        command: gunicorn snacks_project.wsgi:application --bind 127.0.0.1:8000 --workers 4
        volumes:
            - .:/code
        ports:
            - "8000:8000"